[package]
name = "syscall_handler"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-vm.workspace = true
thiserror.workspace = true
types.workspace = true
num-integer.workspace = true
keccak.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
serde.workspace = true