# See: https://rust-lang.github.io/rustfmt
edition = "2021"
max_width = 140
use_field_init_shorthand = true

# Import organization (nightly features)
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true

# Code style
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100