[workspace]
version = "0.1.0"
edition = "2023_11"

members = [
    "examples/average",
    "examples/hello_world",
    "examples/starkgate",
    "hdp_cairo",
    "tests",
]

[workspace.dependencies]
starknet = "2.9.2"
hdp_cairo = { path = "hdp_cairo" }