[workspace]
version = "0.1.0"
edition = "2023_11"

members = [
    "examples",
    "hdp_cairo",
    "tests",
]

[workspace.dependencies]
alexandria_bytes = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git" }
cairo_test = "2.9.2"
hdp_cairo = { path = "hdp_cairo" }
starknet = "2.9.2"

[workspace.tool.fmt]
sort-module-level-items = true