[workspace]
name = "hdp_cairo"
version = "0.1.0"
edition = "2023_11"

members = [
    "cairo",
    "src/contracts/dry_run_test",
    "src/contracts/dry_run_private_inputs",
    "src/contracts/not_continues_blocks",
]

[workspace.dependencies]
hdp_cairo = { path = "cairo" }