[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
reqwest.workspace = true
serde_json.workspace = true
serde_with.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true