[package]
name = "example_mainnet"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = { workspace = true }
hdp_cairo = { workspace = true }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs = false

[dev-dependencies]
cairo_test = { workspace = true }

[tool]
fmt.workspace = true
