[package]
name = "example_injected_state"
version = "0.1.0"
edition = "2023_11"

[dependencies]
hdp_cairo = { workspace = true }
starknet = { workspace = true }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
allowed-libfuncs = false

[dev-dependencies]
cairo_test = { workspace = true }

[tool]
fmt.workspace = true
