[package]
name = "provider"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
reqwest.workspace = true