[package]
name = "sound_run"
version = "0.1.0"
edition = "2021"

[dependencies]
sound_hint_processor.workspace = true
cairo-vm.workspace = true
clap.workspace = true
thiserror.workspace = true
serde_json.workspace = true

types.workspace = true
hints.workspace = true