[book]
authors = ["Okm165"]
language = "en"
multilingual = false
src = "src"
title = "Herodotus Data Processor Documentation"

[output.html]
git-repository-url = "https://github.com/HerodotusDev/hdp-cairo"