[book]
authors = ["Okm165"]
language = "en"
multilingual = false
src = "src"
title = "HDP Cairo Documentation"
description = "Provable historical blockchain data in Cairo"

[output.html]
git-repository-url = "https://github.com/HerodotusDev/hdp-cairo"