[package]
name = "hdp_cairo"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.3"

[lib]
name = "hdp_cairo"
target = "starknet-contract"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true