[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
cairo-vm.workspace = true
dry_hint_processor.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing-subscriber.workspace = true
types.workspace = true