name: rust-vm-CI

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  check:
    name: Format and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Set up Cairo
        run: make setup

      - name: Run fmt check
        run: cargo fmt --all -- --check

      - name: Run clippy check
        run: cargo clippy -- -D warnings

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Scarb
        uses: software-mansion/setup-scarb@v1

      - name: Set up Cairo
        run: make setup

      - name: Install Nextest
        uses: taiki-e/install-action@nextest

      - name: Build Test Contracts
        run: scarb build

      - name: Run Nextest Tests
        env:
            RPC: ${{ secrets.RPC_URL }}
        run: cargo nextest run
