name: rust-vm-CI

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  check:
    name: Format and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Cairo
        run: make setup

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy -- -D warnings

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Set up Cairo
        run: make setup

      - name: Install Nextest
        uses: taiki-e/install-action@nextest

      - name: Run Nextest Tests
        run: cargo nextest run
